#line 2 "bincfg/bincfg_lex.c"

#line 4 "bincfg/bincfg_lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer bc__create_buffer
#define yy_delete_buffer bc__delete_buffer
#define yy_flex_debug bc__flex_debug
#define yy_init_buffer bc__init_buffer
#define yy_flush_buffer bc__flush_buffer
#define yy_load_buffer_state bc__load_buffer_state
#define yy_switch_to_buffer bc__switch_to_buffer
#define yyin bc_in
#define yyleng bc_leng
#define yylex bc_lex
#define yylineno bc_lineno
#define yyout bc_out
#define yyrestart bc_restart
#define yytext bc_text
#define yywrap bc_wrap
#define yyalloc bc_alloc
#define yyrealloc bc_realloc
#define yyfree bc_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE bc_restart(bc_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int bc_leng;

extern FILE *bc_in, *bc_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up bc_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up bc_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via bc_restart()), so that the user can continue scanning by
	 * just pointing bc_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when bc_text is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int bc_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow bc_wrap()'s to do buffer switches
 * instead of setting up a fresh bc_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void bc_restart (FILE *input_file  );
void bc__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE bc__create_buffer (FILE *file,int size  );
void bc__delete_buffer (YY_BUFFER_STATE b  );
void bc__flush_buffer (YY_BUFFER_STATE b  );
void bc_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void bc_pop_buffer_state (void );

static void bc_ensure_buffer_stack (void );
static void bc__load_buffer_state (void );
static void bc__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER bc__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE bc__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE bc__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE bc__scan_bytes (yyconst char *bytes,int len  );

void *bc_alloc (yy_size_t  );
void *bc_realloc (void *,yy_size_t  );
void bc_free (void *  );

#define yy_new_buffer bc__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        bc_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            bc__create_buffer(bc_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        bc_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            bc__create_buffer(bc_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define bc_wrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *bc_in = (FILE *) 0, *bc_out = (FILE *) 0;

typedef int yy_state_type;

extern int bc_lineno;

int bc_lineno = 1;

extern char *bc_text;
#define yytext_ptr bc_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up bc_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	bc_leng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 71
#define YY_END_OF_BUFFER 72
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[215] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   44,   44,   56,   56,   56,   56,
       72,   69,   68,   66,   69,   64,   63,   59,   65,   62,
       60,   70,   70,   17,   15,   16,   18,   67,   59,   60,
       67,   70,   70,   70,   46,   44,   45,   25,   26,   27,
       28,   29,   30,   31,   32,   43,   24,   33,   34,   35,
       36,   37,   38,   39,   40,   41,   42,   23,   55,   56,
       53,   57,   51,   50,   47,   52,   57,   48,   54,   47,
       48,   69,   68,   61,   58,   59,   60,   65,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   14,

       17,   16,   67,   67,   59,   60,    0,    0,    0,    0,
       44,   43,   55,   56,   49,   47,   48,   52,   47,   48,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   19,   20,   21,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   22,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    8,    0,    0,
        0,    0,    0,    0,    6,    0,    0,    0,    0,    0,
        5,    0,    0,    0,    0,    0,    0,    0,    0,   12,
        0,    0,    0,    0,    0,    0,   13,    0,    0,    0,

        2,    3,   10,    4,    0,    0,    9,    7,    0,    0,
        0,    1,   11,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    4,    1,    1,    1,    1,
        1,    1,    1,    5,    6,    1,    1,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   15,    1,   16,    1,
       17,    1,    1,   18,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   35,   42,   35,
       43,    1,   44,    1,    1,    1,   45,   46,   47,   48,

       49,   24,   50,   51,   52,   53,   54,   55,   56,   57,
       58,   59,   35,   60,   61,   62,   63,   64,   65,   35,
       66,   35,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[67] =
    {   0,
        1,    2,    3,    4,    5,    5,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    7,    5,    1,    6,    6,
        6,    6,    6,    6,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    7,    2,    6,    6,    6,    6,    6,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5
    } ;

static yyconst flex_int16_t yy_base[226] =
    {   0,
        0,    0,   64,   65,  108,    0,    0,    0,   35,   36,
       36,   37,    0,    0,  174,    0,  240,    0,  306,    0,
      549,   70,  545,  896,   75,  896,  366,  375,    0,  896,
      393,  896,  405,    0,  896,    0,  896,   81,  466,  402,
      542,  373,  410,   42,  896,  508,  896,  896,  896,  896,
      896,  896,  896,  896,  896,    0,  896,  896,  896,  896,
      896,  896,  896,  896,  896,  896,  896,  896,    0,  507,
      896,    0,  896,  896,  509,    0,  896,  484,  896,  552,
      493,   85,  481,   86,  527,    0,    0,    0,  438,  412,
      427,  499,  386,  504,  558,  421,  508,  548,  560,  896,

        0,    0,  590,  463,    0,  575,  413,  494,  514,  565,
      448,    0,    0,  446,    0,    0,  602,    0,    0,    0,
      587,  586,  585,  581,  582,  606,  605,  607,  610,  598,
      616,  612,  405,  896,  896,  896,  626,  625,  622,  631,
      634,  637,  640,  638,  647,  649,  652,  650,  668,  896,
      661,  670,  669,  665,  403,  674,  689,  682,  684,  690,
      691,  397,  696,  695,  705,  706,  720,  896,  396,  699,
      713,  708,  734,  729,  896,  721,  739,  733,  391,  746,
      896,  744,  732,  741,  584,  756,  388,  743,  745,  896,
      768,  349,  347,   62,   61,  763,  896,  780,   54,   48,

      896,  896,  896,  896,  781,  772,  896,  896,  775,   47,
       40,  896,  896,  896,  829,  836,  842,  849,  856,  862,
      869,  875,  882,   77,  888
    } ;

static yyconst flex_int16_t yy_def[226] =
    {   0,
      214,    1,  215,  215,  214,    5,    1,    1,    1,    1,
        1,    1,    1,    1,  214,   15,  214,   17,  214,   19,
      214,  214,  214,  214,  216,  214,  214,  214,  217,  214,
       28,  214,  218,  219,  214,  220,  214,  221,  221,   39,
      221,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  222,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  223,  214,
      214,  224,  214,  214,  223,  225,  214,   75,  214,  214,
       80,  214,  214,  216,  214,   28,   31,  217,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  214,

      219,  220,  221,  221,   39,   39,  214,  214,  214,  214,
      214,  222,  223,  214,  224,   75,   75,  225,   80,   81,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  214,  214,  214,  214,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  214,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  214,  218,  218,
      218,  218,  218,  218,  214,  218,  218,  218,  218,  218,
      214,  218,  218,  218,  218,  218,  218,  218,  218,  214,
      218,  218,  218,  218,  218,  218,  214,  218,  218,  218,

      214,  214,  214,  214,  218,  218,  214,  214,  218,  218,
      218,  214,  214,    0,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214
    } ;

static yyconst flex_int16_t yy_nxt[963] =
    {   0,
       22,   23,   24,   25,   26,   27,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   29,   30,   22,   31,   31,
       31,   31,   31,   31,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   33,   32,   31,   31,   31,   31,   31,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   35,   35,   42,   42,
       82,   43,   43,   82,  110,   82,   44,   44,   82,   36,
       36,  103,  115,  213,   82,   82,  214,   82,   82,  214,
      212,  208,   82,   42,   42,   43,   43,  207,  103,  110,

       44,   44,   82,  214,  204,  203,   37,   37,   38,   23,
       24,   25,   26,   27,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   29,   30,   38,   40,   40,   40,   40,
       40,   40,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       33,   32,   40,   40,   40,   40,   40,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   45,   46,   47,   45,   45,   45,
       48,   49,   50,   51,   52,   53,   54,   55,   45,   56,
       45,   57,   58,   59,   45,   45,   45,   45,   45,   45,

       60,   45,   45,   61,   45,   45,   62,   63,   45,   64,
       45,   65,   45,   66,   67,   45,   68,   45,   58,   59,
       45,   45,   45,   45,   45,   60,   45,   45,   61,   45,
       45,   62,   63,   64,   45,   65,   45,   66,   67,   45,
       69,   70,   71,   72,   73,   74,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   76,   77,   69,   78,   78,
       78,   78,   78,   78,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   79,   77,   78,   78,   78,   78,   78,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,

       69,   69,   69,   69,   69,   69,   77,   70,   71,   72,
       73,   74,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   76,   77,   77,   81,   81,   81,   81,   81,   81,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   79,   77,
       81,   81,   81,   81,   81,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   86,   86,   86,   86,   86,   86,   86,   86,   86,
      202,  107,  201,   87,   87,   87,   87,   87,   87,   87,

       87,   87,   87,   87,   87,   87,   87,   87,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  107,  124,   87,
       87,   87,   87,   87,   90,   91,   92,  150,  108,  100,
      121,  197,   93,   94,  190,   95,   96,  133,   97,  181,
      175,   98,  109,  124,   99,  122,  168,  114,  100,  111,
       90,   91,   92,  150,  108,  100,  121,   93,   94,  128,
       95,   96,  133,   97,  100,   98,  214,  109,   99,  214,
      100,  122,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  100,   83,  128,  106,  106,  106,  106,  106,  106,
      117,  117,  117,  117,  117,  117,  117,  117,  117,  120,

      120,  120,  120,  120,  120,  120,  120,  120,  114,  111,
      106,  106,  106,  106,  106,  116,  116,  116,  116,  116,
      116,  116,  116,  116,  134,  123,  125,  117,  117,  117,
      117,  117,  117,   85,   85,   85,   85,   85,   85,   85,
       85,   85,  100,  129,  135,  214,   83,  100,  214,  134,
      123,  100,  125,  117,  117,  117,  117,  117,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  129,  130,  135,
      120,  120,  120,  120,  120,  120,  126,  214,  131,  214,
      127,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      103,  100,  132,   82,  130,  136,  120,  120,  120,  120,

      120,  100,  126,  100,  131,  195,  127,  103,  117,  117,
      117,  117,  117,  117,  117,  117,  117,  132,  137,  138,
      136,  139,  140,  141,  100,  100,  142,  100,  100,  100,
      100,  195,  146,  147,  214,  144,  214,  145,  149,  143,
      153,  100,  214,  137,  138,  139,  140,  141,  100,  100,
      100,  148,  142,  100,  151,  100,  158,  147,  146,  100,
      144,  152,  145,  149,  143,  100,  153,  154,  100,  100,
      155,  214,  156,  157,  100,  148,  159,  100,  160,  151,
      100,  100,  158,  100,  161,  152,  162,  214,  163,  214,
      100,  154,  100,  100,  155,  100,  156,  164,  157,  165,

      214,  159,  167,  160,  100,  166,  169,  214,  100,  161,
      162,  100,  100,  100,  163,  170,  172,  100,  176,  171,
      174,  164,  173,  214,  165,  100,  167,  100,  184,  166,
      182,  169,  100,  100,  100,  177,  179,  178,  100,  100,
      170,  172,  100,  171,  176,  174,  180,  173,  100,  100,
      183,  100,  185,  189,  184,  182,  100,  187,  186,  177,
      214,  179,  178,  100,  100,  188,  191,  193,  192,  194,
      214,  180,  100,  199,  183,  100,  100,  100,  185,  189,
      198,  187,  100,  186,  100,  196,  100,  100,  100,  100,
      188,  193,  191,  192,  194,  205,  200,  210,  199,  100,

      206,  209,  214,  211,  198,  214,  100,  214,  214,  214,
      196,  100,  214,  214,  214,  100,  214,  214,  100,  214,
      205,  200,  210,  100,  100,  214,  206,  209,  211,   34,
       34,   34,   34,   34,   34,   34,   84,  214,  214,   84,
      214,   84,   88,   88,  214,   88,   88,   88,   88,   89,
       89,   89,   89,   89,   89,   89,  101,  101,  214,  101,
      101,  101,  102,  102,  214,  102,  102,  102,  102,  104,
      214,  214,  104,  104,  104,  112,  112,  214,  112,  112,
      112,  112,  113,  214,  214,  214,  113,  113,  118,  118,
      214,  118,  118,  118,  118,   21,  214,  214,  214,  214,

      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214
    } ;

static yyconst flex_int16_t yy_chk[963] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    4,    9,   10,
       22,   11,   12,   22,   44,   25,   11,   12,   25,    3,
        4,   38,  224,  211,   38,   82,   84,   22,   82,   84,
      210,  200,   25,    9,   10,   11,   12,  199,   38,   44,

       11,   12,   82,   84,  195,  194,    3,    4,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,

       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,

       17,   17,   17,   17,   17,   17,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   28,   28,   28,   28,   28,   28,   28,   28,   28,
      193,   42,  192,   28,   28,   28,   28,   28,   28,   31,

       31,   31,   31,   31,   31,   31,   31,   31,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   42,   93,   28,
       28,   28,   28,   28,   33,   33,   33,  133,   43,   93,
       90,  187,   33,   33,  179,   33,   33,  107,   33,  169,
      162,   33,   43,   93,   33,   91,  155,  114,   33,  111,
       33,   33,   33,  133,   43,   90,   90,   33,   33,   96,
       33,   33,  107,   33,   96,   33,  104,   43,   33,   39,
       91,   91,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   89,   83,   96,   39,   39,   39,   39,   39,   39,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   81,

       81,   81,   81,   81,   81,   81,   81,   81,   70,   46,
       39,   39,   39,   39,   39,   75,   75,   75,   75,   75,
       75,   75,   75,   75,  108,   92,   94,   75,   75,   75,
       75,   75,   75,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   92,   97,  109,   41,   23,   94,   21,  108,
       92,   97,   94,   75,   75,   75,   75,   75,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   97,   98,  109,
       80,   80,   80,   80,   80,   80,   95,    0,   99,    0,
       95,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      103,   98,   99,  103,   98,  110,   80,   80,   80,   80,

       80,   95,   95,   99,   99,  185,   95,  103,  117,  117,
      117,  117,  117,  117,  117,  117,  117,   99,  121,  122,
      110,  123,  124,  125,  124,  125,  126,  185,  123,  122,
      121,  185,  129,  130,    0,  127,    0,  128,  132,  126,
      139,  130,    0,  121,  122,  123,  124,  125,  127,  126,
      128,  131,  126,  129,  137,  132,  144,  130,  129,  131,
      127,  138,  128,  132,  126,  139,  139,  140,  138,  137,
      141,    0,  142,  143,  140,  131,  145,  141,  146,  137,
      142,  144,  144,  143,  147,  138,  148,    0,  149,    0,
      145,  140,  146,  148,  141,  147,  142,  151,  143,  152,

        0,  145,  154,  146,  151,  153,  156,    0,  154,  147,
      148,  149,  153,  152,  149,  157,  159,  156,  163,  158,
      161,  151,  160,    0,  152,  158,  154,  159,  172,  153,
      170,  156,  157,  160,  161,  164,  166,  165,  164,  163,
      157,  159,  170,  158,  163,  161,  167,  160,  165,  166,
      171,  172,  173,  178,  172,  170,  171,  176,  174,  164,
        0,  166,  165,  167,  176,  177,  180,  183,  182,  184,
        0,  167,  174,  189,  171,  183,  178,  173,  173,  178,
      188,  176,  177,  174,  184,  186,  188,  182,  189,  180,
      177,  183,  180,  182,  184,  196,  191,  206,  189,  186,

      198,  205,    0,  209,  188,    0,  196,    0,    0,    0,
      186,  191,    0,    0,    0,  206,    0,    0,  209,    0,
      196,  191,  206,  198,  205,    0,  198,  205,  209,  215,
      215,  215,  215,  215,  215,  215,  216,    0,    0,  216,
        0,  216,  217,  217,    0,  217,  217,  217,  217,  218,
      218,  218,  218,  218,  218,  218,  219,  219,    0,  219,
      219,  219,  220,  220,    0,  220,  220,  220,  220,  221,
        0,    0,  221,  221,  221,  222,  222,    0,  222,  222,
      222,  222,  223,    0,    0,    0,  223,  223,  225,  225,
        0,  225,  225,  225,  225,  214,  214,  214,  214,  214,

      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int bc__flex_debug;
int bc__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *bc_text;
#line 1 "bincfg/bincfg_lex.l"
/* Scanner for INTVPC .CFG files */









#line 22 "bincfg/bincfg_lex.l"

/* put any #includes here */
#include "config.h"
#include "bincfg/bincfg.h"
#include "bincfg/bincfg_grmr.tab.h"


#define bc_lex bc_lex1

int  bc_line_no = 1;
int  bc_dec; 
int  bc_hex;
char *bc_txt = NULL;
static int bc_txt_alloc = 0;


#define YYTEXT_TO_BC_TXT \
        do {                                                            \
            if (bc_leng > bc_txt_alloc)                                  \
            {                                                           \
                if (bc_txt)                                             \
                {                                                       \
                    bc_txt_alloc = bc_txt_alloc << 1;                   \
                    free(bc_txt);                                       \
                } else                                                  \
                    bc_txt_alloc = 256;                                 \
                                                                        \
                bc_txt = malloc(bc_txt_alloc);                          \
                                                                        \
                if (!bc_txt)                                            \
                    return TOK_ERROR_OOM;                               \
            }                                                           \
                                                                        \
            strcpy(bc_txt, bc_text);                                     \
        } while (0)



#line 817 "bincfg/bincfg_lex.c"

#define INITIAL 0
#define SEC_IGN 1
#define SEC_VAR 2
#define SEC_BSW 3
#define SEC_MAP 4
#define SEC_ATR 5
#define SEC_PRL 6
#define SEC_MC0 7
#define SEC_MC1 8
#define SEC_MC2 9

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int bc_lex_destroy (void );

int bc_get_debug (void );

void bc_set_debug (int debug_flag  );

YY_EXTRA_TYPE bc_get_extra (void );

void bc_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *bc_get_in (void );

void bc_set_in  (FILE * in_str  );

FILE *bc_get_out (void );

void bc_set_out  (FILE * out_str  );

int bc_get_leng (void );

char *bc_get_text (void );

int bc_get_lineno (void );

void bc_set_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int bc_wrap (void );
#else
extern int bc_wrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( bc_text, bc_leng, 1, bc_out )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( bc_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( bc_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, bc_in))==0 && ferror(bc_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(bc_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int bc_lex (void);

#define YY_DECL int bc_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after bc_text and bc_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 65 "bincfg/bincfg_lex.l"

                   
 
/* -------------------------------------------------------------------- */
/*  Rules for identifying section headers.                              */
/* -------------------------------------------------------------------- */
 
#line 1019 "bincfg/bincfg_lex.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! bc_in )
			bc_in = stdin;

		if ( ! bc_out )
			bc_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			bc_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				bc__create_buffer(bc_in,YY_BUF_SIZE );
		}

		bc__load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of bc_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 215 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 214 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 72 "bincfg/bincfg_lex.l"
{   BEGIN(SEC_BSW); return  TOK_SEC_BANKSWITCH;     }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 73 "bincfg/bincfg_lex.l"
{   BEGIN(SEC_MAP); return  TOK_SEC_MAPPING;        }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 74 "bincfg/bincfg_lex.l"
{   BEGIN(SEC_ATR); return  TOK_SEC_MEMATTR;        }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 75 "bincfg/bincfg_lex.l"
{   BEGIN(SEC_PRL); return  TOK_SEC_PRELOAD;        }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 77 "bincfg/bincfg_lex.l"
{   BEGIN(SEC_MC0); return  TOK_SEC_MACRO;          }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 79 "bincfg/bincfg_lex.l"
{   BEGIN(SEC_VAR); return  TOK_SEC_VARS;           }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 80 "bincfg/bincfg_lex.l"
{   BEGIN(SEC_VAR); return  TOK_SEC_JOYSTICK;       }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 81 "bincfg/bincfg_lex.l"
{   BEGIN(SEC_VAR); return  TOK_SEC_KEYS;           }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 82 "bincfg/bincfg_lex.l"
{   BEGIN(SEC_VAR); return  TOK_SEC_CAPSLOCK;       }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 83 "bincfg/bincfg_lex.l"
{   BEGIN(SEC_VAR); return  TOK_SEC_NUMLOCK;        }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 84 "bincfg/bincfg_lex.l"
{   BEGIN(SEC_VAR); return  TOK_SEC_SCROLLLOCK;     }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 86 "bincfg/bincfg_lex.l"
{   BEGIN(SEC_IGN); return  TOK_SEC_DISASM;         }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 87 "bincfg/bincfg_lex.l"
{   BEGIN(SEC_IGN); return  TOK_SEC_VOICES;         }
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 89 "bincfg/bincfg_lex.l"
{   BEGIN(SEC_IGN); return  TOK_SEC_UNKNOWN;        }
	YY_BREAK
 
/* -------------------------------------------------------------------- */
/*  Mini-scanner for ignored sections:  Just eat them right up.         */
/* -------------------------------------------------------------------- */

case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
#line 96 "bincfg/bincfg_lex.l"
{   bc_line_no++; /* eat newlines */                }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 97 "bincfg/bincfg_lex.l"
{   /* eat comments */                              }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 98 "bincfg/bincfg_lex.l"
{   /* eat non-section openers. */                  }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 99 "bincfg/bincfg_lex.l"
{   yyless(0);  BEGIN(INITIAL); return '\n';        }
	YY_BREAK
 
/* -------------------------------------------------------------------- */
/*  Keywords that are only valid in memory-attribute section.           */
/* -------------------------------------------------------------------- */

case 19:
YY_RULE_SETUP
#line 106 "bincfg/bincfg_lex.l"
{   return TOK_RAM;                                 }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 107 "bincfg/bincfg_lex.l"
{   return TOK_ROM;                                 }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 108 "bincfg/bincfg_lex.l"
{   return TOK_WOM;                                 }
	YY_BREAK
 
/* -------------------------------------------------------------------- */
/*  Keywords that are only valid in the mapping section.                */
/* -------------------------------------------------------------------- */

case 22:
YY_RULE_SETUP
#line 115 "bincfg/bincfg_lex.l"
{   return TOK_PAGE;                                }
	YY_BREAK
 
/* -------------------------------------------------------------------- */
/*  Keywords that are only valid in the mapping section.                */
/* -------------------------------------------------------------------- */

case 23:
YY_RULE_SETUP
#line 122 "bincfg/bincfg_lex.l"
{   yyless(0); BEGIN(INITIAL);   /*]*/              }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 123 "bincfg/bincfg_lex.l"
{   return TOK_MAC_QUIET;                           }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 124 "bincfg/bincfg_lex.l"
{   BEGIN(SEC_MC2); bc_hex=0; return TOK_MAC_REG;   }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 125 "bincfg/bincfg_lex.l"
{   BEGIN(SEC_MC2); bc_hex=1; return TOK_MAC_REG;   }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 126 "bincfg/bincfg_lex.l"
{   BEGIN(SEC_MC2); bc_hex=2; return TOK_MAC_REG;   }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 127 "bincfg/bincfg_lex.l"
{   BEGIN(SEC_MC1); bc_hex=3; return TOK_MAC_REG;   }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 128 "bincfg/bincfg_lex.l"
{   BEGIN(SEC_MC2); bc_hex=4; return TOK_MAC_REG;   }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 129 "bincfg/bincfg_lex.l"
{   BEGIN(SEC_MC2); bc_hex=5; return TOK_MAC_REG;   }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 130 "bincfg/bincfg_lex.l"
{   BEGIN(SEC_MC2); bc_hex=6; return TOK_MAC_REG;   }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 131 "bincfg/bincfg_lex.l"
{   BEGIN(SEC_MC2); bc_hex=7; return TOK_MAC_REG;   }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 132 "bincfg/bincfg_lex.l"
{   BEGIN(SEC_MC2); return TOK_MAC_AHEAD;           }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 133 "bincfg/bincfg_lex.l"
{   BEGIN(SEC_MC2); return TOK_MAC_BLANK;           }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 134 "bincfg/bincfg_lex.l"
{   BEGIN(SEC_MC2); return TOK_MAC_INSPECT;         }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 135 "bincfg/bincfg_lex.l"
{   BEGIN(SEC_MC1); return TOK_MAC_LOAD;            }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 136 "bincfg/bincfg_lex.l"
{   BEGIN(SEC_MC2); return TOK_MAC_RUNTO;           }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 137 "bincfg/bincfg_lex.l"
{   BEGIN(SEC_MC2); return TOK_MAC_POKE;            }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 138 "bincfg/bincfg_lex.l"
{   BEGIN(SEC_MC2); return TOK_MAC_RUN;             }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 139 "bincfg/bincfg_lex.l"
{   BEGIN(SEC_MC2); return TOK_MAC_TRACE;           }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 140 "bincfg/bincfg_lex.l"
{   BEGIN(SEC_MC2); return TOK_MAC_VIEW;            }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 141 "bincfg/bincfg_lex.l"
{   BEGIN(SEC_MC1); return TOK_MAC_WATCH;           }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 142 "bincfg/bincfg_lex.l"
{   /* ignore comments.       */                    }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 143 "bincfg/bincfg_lex.l"
{   /* ignore whitespace.     */                    }
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 144 "bincfg/bincfg_lex.l"
{   bc_line_no++; return '\n';                      }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 145 "bincfg/bincfg_lex.l"
{   /* ignore unknown lines.  */                    }
	YY_BREAK
 
/* -------------------------------------------------------------------- */
/*  Special secondary, tertiary states for macro processing.  Grrr...   */
/*  We enter this state after parsing the first 'name' on a line.       */
/*  This keeps hex ranges that aren't $ adorned from turning into       */
/*  TOK_NAMEs.  Too much of the grammar comes into the lexer.  :-P      */
/* -------------------------------------------------------------------- */

case 47:
YY_RULE_SETUP
#line 156 "bincfg/bincfg_lex.l"
{   
                                    BEGIN(SEC_MC2);
                                    bc_dec = atoi(bc_text);
                                    sscanf(bc_text    , "%x", &bc_hex); 
                                    YYTEXT_TO_BC_TXT;
                                    return  TOK_DEC;    
                                }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 163 "bincfg/bincfg_lex.l"
{   
                                    BEGIN(SEC_MC2);
                                    bc_dec = atoi(bc_text);
                                    sscanf(bc_text    , "%x", &bc_hex); 
                                    YYTEXT_TO_BC_TXT;
                                    return  TOK_HEX;    
                                }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 170 "bincfg/bincfg_lex.l"
{   
                                    BEGIN(SEC_MC2);
                                    bc_dec = atoi(bc_text + 1);
                                    sscanf(bc_text + 1, "%x", &bc_hex); 
                                    YYTEXT_TO_BC_TXT;
                                    return  TOK_HEX;    
                                }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 177 "bincfg/bincfg_lex.l"
{   BEGIN(SEC_MC2); return '-';                 }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 178 "bincfg/bincfg_lex.l"
{   BEGIN(SEC_MC2); return ',';                 }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 179 "bincfg/bincfg_lex.l"
{   BEGIN(SEC_MC2); /* eat comments.  */        }
	YY_BREAK
case 53:
/* rule 53 can match eol */
YY_RULE_SETUP
#line 180 "bincfg/bincfg_lex.l"
{   bc_line_no++; BEGIN(SEC_MC0); return '\n';  }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 181 "bincfg/bincfg_lex.l"
{   yyless(0); BEGIN(INITIAL);   /*]*/          }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 183 "bincfg/bincfg_lex.l"
{   
                                    BEGIN(SEC_MC2);
                                    YYTEXT_TO_BC_TXT;                
                                    return  TOK_NAME;   
                                }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 189 "bincfg/bincfg_lex.l"
{ /* ignore whitespace. */                    }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 190 "bincfg/bincfg_lex.l"
{   YYTEXT_TO_BC_TXT; return TOK_ERROR_BAD;     }
	YY_BREAK
 
/* -------------------------------------------------------------------- */
/*  Main scanner with common rules across most sections.                */
/* -------------------------------------------------------------------- */

case 58:
YY_RULE_SETUP
#line 197 "bincfg/bincfg_lex.l"
{   
                bc_dec = atoi(bc_text);
                sscanf(bc_text + 1, "%x", &bc_hex); 
                YYTEXT_TO_BC_TXT;
                return  TOK_DECONLY;    
            }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 203 "bincfg/bincfg_lex.l"
{   
                bc_dec = atoi(bc_text);
                sscanf(bc_text    , "%x", &bc_hex); 
                YYTEXT_TO_BC_TXT;
                return  TOK_DEC;    
            }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 209 "bincfg/bincfg_lex.l"
{   
                bc_dec = atoi(bc_text);
                sscanf(bc_text    , "%x", &bc_hex); 
                YYTEXT_TO_BC_TXT;
                return  TOK_HEX;    
            }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 215 "bincfg/bincfg_lex.l"
{   
                bc_dec = atoi(bc_text + 1);
                sscanf(bc_text + 1, "%x", &bc_hex); 
                YYTEXT_TO_BC_TXT;
                return  TOK_HEX;    
            }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 221 "bincfg/bincfg_lex.l"
{   return '=';                                             }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 222 "bincfg/bincfg_lex.l"
{   return '-';                                             }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 223 "bincfg/bincfg_lex.l"
{   return ',';                                             }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 224 "bincfg/bincfg_lex.l"
{   /* eat comments.  */                                    }
	YY_BREAK
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 225 "bincfg/bincfg_lex.l"
{   bc_line_no++;
                if (YY_START == SEC_MC1) BEGIN(SEC_MC0);
                return '\n';        /* comments and newlines are same */
            }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 230 "bincfg/bincfg_lex.l"
{   
                YYTEXT_TO_BC_TXT;                
                return  TOK_NAME;   
            }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 235 "bincfg/bincfg_lex.l"
{   /* eat whitespace */                                    }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 236 "bincfg/bincfg_lex.l"
{ YYTEXT_TO_BC_TXT; return TOK_ERROR_BAD;  }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 237 "bincfg/bincfg_lex.l"
{ YYTEXT_TO_BC_TXT; return TOK_ERROR_BAD;  }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 239 "bincfg/bincfg_lex.l"
ECHO;
	YY_BREAK
#line 1539 "bincfg/bincfg_lex.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(SEC_IGN):
case YY_STATE_EOF(SEC_VAR):
case YY_STATE_EOF(SEC_BSW):
case YY_STATE_EOF(SEC_MAP):
case YY_STATE_EOF(SEC_ATR):
case YY_STATE_EOF(SEC_PRL):
case YY_STATE_EOF(SEC_MC0):
case YY_STATE_EOF(SEC_MC1):
case YY_STATE_EOF(SEC_MC2):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed bc_in at a new source and called
			 * bc_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = bc_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( bc_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * bc_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of bc_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					bc_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			bc_restart(bc_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) bc_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 215 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 215 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 214);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					bc_restart(bc_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( bc_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve bc_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void bc_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        bc_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            bc__create_buffer(bc_in,YY_BUF_SIZE );
	}

	bc__init_buffer(YY_CURRENT_BUFFER,input_file );
	bc__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void bc__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		bc_pop_buffer_state();
	 *		bc_push_buffer_state(new_buffer);
     */
	bc_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	bc__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (bc_wrap()) processing, but the only time this flag
	 * is looked at is after bc_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void bc__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	bc_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE bc__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) bc_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in bc__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) bc_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in bc__create_buffer()" );

	b->yy_is_our_buffer = 1;

	bc__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with bc__create_buffer()
 * 
 */
    void bc__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		bc_free((void *) b->yy_ch_buf  );

	bc_free((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a bc_restart() or at EOF.
 */
    static void bc__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	bc__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then bc__init_buffer was _probably_
     * called from bc_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void bc__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		bc__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void bc_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	bc_ensure_buffer_stack();

	/* This block is copied from bc__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from bc__switch_to_buffer. */
	bc__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void bc_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	bc__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		bc__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void bc_ensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)bc_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in bc_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)bc_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in bc_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE bc__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) bc_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in bc__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	bc__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to bc_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       bc__scan_bytes() instead.
 */
YY_BUFFER_STATE bc__scan_string (yyconst char * yystr )
{
    
	return bc__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to bc_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE bc__scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) bc_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in bc__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = bc__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in bc__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up bc_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		bc_text[bc_leng] = (yy_hold_char); \
		(yy_c_buf_p) = bc_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		bc_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int bc_get_lineno  (void)
{
        
    return bc_lineno;
}

/** Get the input stream.
 * 
 */
FILE *bc_get_in  (void)
{
        return bc_in;
}

/** Get the output stream.
 * 
 */
FILE *bc_get_out  (void)
{
        return bc_out;
}

/** Get the length of the current token.
 * 
 */
int bc_get_leng  (void)
{
        return bc_leng;
}

/** Get the current token.
 * 
 */

char *bc_get_text  (void)
{
        return bc_text;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void bc_set_lineno (int  line_number )
{
    
    bc_lineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see bc__switch_to_buffer
 */
void bc_set_in (FILE *  in_str )
{
        bc_in = in_str ;
}

void bc_set_out (FILE *  out_str )
{
        bc_out = out_str ;
}

int bc_get_debug  (void)
{
        return bc__flex_debug;
}

void bc_set_debug (int  bdebug )
{
        bc__flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from bc_lex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    bc_in = stdin;
    bc_out = stdout;
#else
    bc_in = (FILE *) 0;
    bc_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * bc_lex_init()
     */
    return 0;
}

/* bc_lex_destroy is for both reentrant and non-reentrant scanners. */
int bc_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		bc__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		bc_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	bc_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * bc_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *bc_alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *bc_realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void bc_free (void * ptr )
{
	free( (char *) ptr );	/* see bc_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 239 "bincfg/bincfg_lex.l"



#undef bc_lex

/* We wrap bc_lex with a wrapper that outputs an extra newline at EOF */
int bc_lex(void)
{
    static int need_nl = 1;
    int token = bc_lex1();

    if (token <= 0 && need_nl) 
    { 
        need_nl = 0; 
        return '\n'; 
    }
    if (token > 0) 
    {   
        need_nl = 1; 
    }

    return token;
}

/* ======================================================================== */
/*  This program is free software; you can redistribute it and/or modify    */
/*  it under the terms of the GNU General Public License as published by    */
/*  the Free Software Foundation; either version 2 of the License, or       */
/*  (at your option) any later version.                                     */
/*                                                                          */
/*  This program is distributed in the hope that it will be useful,         */
/*  but WITHOUT ANY WARRANTY; without even the implied warranty of          */
/*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU       */
/*  General Public License for more details.                                */
/*                                                                          */
/*  You should have received a copy of the GNU General Public License       */
/*  along with this program; if not, write to the Free Software             */
/*  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.               */
/* ======================================================================== */
/*                 Copyright (c) 2003-+Inf, Joseph Zbiciak                  */
/* ======================================================================== */

